<?xml version='1.0'?>

<!DOCTYPE stylesheet 
[

<!-- ============== HOME ============== -->
<!ENTITY xsl_ns_base_cygwin "/cygdrive/e/Dev_Root/docbook/tools/docbook-xsl-ns-1.77.1">

<!-- ============== OFFICE ============== -->
<!--<!ENTITY xsl_ns_base_cygwin "/home/CLi/develop/docbook/tools/docbook-xsl-ns-1.77.1">-->
<!ENTITY xsl_ns_base_cygwin "/home/CLi/develop/docbook/tools/docbook-xsl-ns-1.77.1">

<!-- ============== UNIFY ============== -->
<!-- <!ENTITY xsl_ns_base_cygwin "/home/develop/docbook/tools_root/docbook-xsl-ns-1.76.1"> -->
<!-- <!ENTITY xsl_ns_base_cygwin "/home/develop/docbook/tools_root/docbook-xsl-ns-1.77.1"> -->
<!--<!ENTITY xsl_ns_base_cygwin "E:/Dev_Root/docbook/tools/docbook-xsl-ns-1.77.1">-->

]
>

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version='1.0'>

<xsl:import href="file://&xsl_ns_base_cygwin;/html/chunk.xsl"/>
<!--<xsl:import href="file://E:/Dev_Root/docbook/tools/docbook-xsl-ns-1.77.1/html/chunk.xsl"/>-->
<xsl:import href="../common_html.xsl"/>

<!--============================================================================
misc setting
=============================================================================-->

<xsl:param name="chunker.output.encoding" select="'UTF-8'"/>
<!-- html source code contain indent == formatted -->
<xsl:param name="chunker.output.indent" select="'yes'"/>

<!-- now put all path related settings into makefile -->
<!-- <xsl:param name="base.dir">&output_base_cmd;/html/multi/</xsl:param> -->

<!-- has moved following to makefile
<xsl:param name="navig.graphics">1</xsl:param>
<xsl:param name="navig.graphics.extension">.png</xsl:param>
<xsl:param name="navig.graphics.path">images/system/</xsl:param>
-->

<!--
http://docbook.sourceforge.net/release/xsl/1.77.1/doc/html/use.id.as.filename.html
the filename of chunk elements that have IDs will be derived from the ID value
-->
<xsl:param name="use.id.as.filename">1</xsl:param>

<!--
http://docbook.sourceforge.net/release/xsl/1.77.1/doc/html/generate.manifest.html
a list of HTML files generated by the stylesheet transformation is written to the file named by the manifest parameter.
-->
<xsl:param name="generate.manifest">1</xsl:param>

<!--
http://docbook.sourceforge.net/release/xsl/1.77.1/doc/html/manifest.html
Name of manifest file
has set this value in docbook.mk
<xsl:param name="manifest">HTML.manifest</xsl:param>
-->

<!--
http://docbook.sourceforge.net/release/xsl/1.77.1/doc/html/root.filename.html
The root.filename is the base filename for the chunk created for the root of each document processed.
-->
<xsl:param name="root.filename">index</xsl:param>

</xsl:stylesheet>